### ISSUE TITLE
bug-Front end fails with correct configuration.

### ISSUE THREAD

**Issue by arokapil** [NotoriousPyro/open-metaverse-pool-www#1]
Missing: 
routes/application.js: line 35, col 14, 'applicationTimer' used out of scope.

code snippet
    setupController: function(controller, model) {
        this._super(controller, model);
        if (!applicationTimer) {
            var applicationTimer = Ember.run.later(this, this.refresh, 15000);
        }
    },

 resetController: function(controller, isExiting, transition) {
        this._super.apply(this, arguments);
        if (isExiting) {
            Ember.run.cancel(this.applicationTimer);
        }
    }
routes/application.js: line 40, col 54, 'transition' is defined but never used.

Front end does not load : Browser  logs.
ember.debug.js:25010 Uncaught TypeError: Cannot convert object to primitive value
    at Array.toString (:8082/native)
    at Object.toString (ember.debug.js:25010)
    at Object.set (ember.debug.js:23517)
    at Class.set (ember.debug.js:36509)
    at Class.willRender [as _super] (ember.debug.js:9157)
    at Class.willRender (link-component.js:11)
    at Class.superWrapper [as willRender] (ember.debug.js:24805)
    at Class.trigger (ember.debug.js:43731)
    at Class.superWrapper [as trigger] (ember.debug.js:24805)
    at Renderer.componentWillRender (ember.debug.js:14621)

**Comment by NotoriousPyro** [comment]
What version of Ember?

**Comment by NotoriousPyro** [comment]
Try replacing the line with this:
```if (typeof applicationTimer === "undefined") {```

**Comment by arokapil** [comment]
ember-cli: 2.9.1
node: 8.11.2
os: linux x64

**Comment by NotoriousPyro** [comment]
I think the problem is your nodejs version. I'm using 4.6.2, how did you install it?

**Comment by arokapil** [comment]
The nodejs is working with others.. whenever i change the enviroment js and point to to any other repo's www dest.. example's sammy's www folder .. also i tried following the same step.. i also tried deleting node modules and everything when i install while i change the destination dir. 
npm install -g ember-cli@2.9.1
npm install -g bower
npm install
bower install
./build.sh

listing down the error i get  while i run the ember server.. to deve.. few miner issues i can fix like out of scope and can create a pull request.. if you still feel that is could be related to node version then i can try using same..

controllers/payments.js: line 18, col 20, 'timestamp' used out of scope.
1 error
helpers/divide.js: line 5, col 2, Unnecessary semicolon.
1 error
helpers/format-hashrate.js: line 14, col 9, Unreachable 'break' after 'return'.
helpers/format-hashrate.js: line 15, col 11, Expected a 'break' statement before 'default'.
2 errors
helpers/multiply.js: line 5, col 2, Unnecessary semicolon.
helpers/multiply.js: line 7, col 16, 'Ember' is not defined.
helpers/multiply.js: line 7, col 36, 'devide' is not defined.

3 errors

helpers/simplemath.js: line 8, col 2, Unnecessary semicolon.
helpers/simplemath.js: line 15, col 2, Unnecessary semicolon.

2 errors

models/block.js: line 7, col 13, 'height' is defined but never used.

1 error

routes/application.js: line 36, col 14, 'applicationTimer' used out of scope.
routes/application.js: line 35, col 12, 'applicationTimer' used out of scope.
routes/application.js: line 41, col 54, 'transition' is defined but never used.

3 errors

**Comment by NotoriousPyro** [comment]
It doesn't matter if those ones work, it doesn't matter if sammy's works. This isn't sammy's this is modified by me. I support only the nodejs bundled with Ubuntu.

**Comment by arokapil** [comment]
sure thanks for the promt response, would try the same version now..

**Comment by NotoriousPyro** [comment]
Building successfully:
```
root@metaverse:/bulk/www/metaverse.farm/oep# ./build.sh
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-welcome-page -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-ajax -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-cli-browser-update -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-cli-htmlbars-inline-precompile -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-cli-qunit -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-cli-qunit -> ember-cli-test-loader -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-cli-scroll-to -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-cli-test-loader -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-export-application-global -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-intl -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-intl -> ember-getowner-polyfill -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-intl -> intl-messageformat -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-intl -> intl-messageformat -> intl-messageformat-parser -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-intl -> intl-relativeformat -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-intl -> intl-relativeformat -> intl-messageformat -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-intl -> intl-relativeformat -> intl-messageformat -> intl-messageformat-parser -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-resolver -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-scroll-to-top -> ember-cli-babel
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
⠧ Building[API] Warning: The .read and .rebuild APIs will stop working in the next Broccoli version
[API] Warning: Use broccoli-plugin instead: https://github.com/broccolijs/broccoli-plugin
[API] Warning: Plugin uses .read/.rebuild API: [object Object]
[API] Warning: Plugin uses .read/.rebuild API: [object Object]
⠼ BuildingWARN: Output exceeds 32000 characters
cleaning up...
Built project successfully. Stored in "dist/".
File sizes:
 - intl-fd3157f9024e9ca032251667ebadee67.js: 28.99 KB (10.09 KB gzipped)
 - intl.complete-a7e83dbca7966d18838d8db0a884f009.js: 844.48 KB (176.62 KB gzipped)
 - intl.min-50b782c1f6d9a43411a8603a5a3d9234.js: 29.05 KB (10.13 KB gzipped)
 - en-us-a53ee708f8f05d570a3095cbc9cec948.js: 23.77 KB (3.85 KB gzipped)
 - open-metaverse-pool-44adb04e0b70cc7b23c2cb263a5f9fcb.js: 201.9 KB (22.51 KB gzipped)
 - open-metaverse-pool-59bc71f74395f0d5c23846763cac5473.css: 3.34 KB (1.05 KB gzipped)
 - vendor-2f058756369b859fa3626ebe08d7b15f.js: 1005.77 KB (210.63 KB gzipped)
 - vendor-6de03bdc10f4c279bf86a435b7667839.css: 144.2 KB (26.03 KB gzipped)
 - browsercheck-9f04135b31b376ccd5866c1fc0caf2f0.js: 119 B (124 B gzipped)
```

**Comment by arokapil** [comment]
build was not an issue.. i see with my case too..

DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-welcome-page -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-ajax -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-cli-browser-update -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-cli-htmlbars-inline-precompile -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-cli-qunit -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-cli-qunit -> ember-cli-test-loader -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-cli-scroll-to -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-cli-test-loader -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-export-application-global -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-intl -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-intl -> ember-getowner-polyfill -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-intl -> intl-messageformat -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-intl -> intl-messageformat -> intl-messageformat-parser -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-intl -> intl-relativeformat -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-intl -> intl-relativeformat -> intl-messageformat -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-intl -> intl-relativeformat -> intl-messageformat -> intl-messageformat-parser -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-resolver -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: open-metaverse-pool -> ember-scroll-to-top -> ember-cli-babel
WARNING: Node v8.11.2 has currently not been tested against Ember CLI and may result in unexpected behaviour.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
⠦ Building[API] Warning: The .read and .rebuild APIs will stop working in the next Broccoli version
[API] Warning: Use broccoli-plugin instead: https://github.com/broccolijs/broccoli-plugin
[API] Warning: Plugin uses .read/.rebuild API: [object Object]
[API] Warning: Plugin uses .read/.rebuild API: [object Object]
⠋ BuildingWARN: Output exceeds 32000 characters
cleaning up...
Built project successfully. Stored in "dist/".
File sizes:
 - intl-fd3157f9024e9ca032251667ebadee67.js: 28.99 KB (10.09 KB gzipped)
 - intl.complete-a7e83dbca7966d18838d8db0a884f009.js: 844.48 KB (176.62 KB gzipped)
 - intl.min-50b782c1f6d9a43411a8603a5a3d9234.js: 29.05 KB (10.13 KB gzipped)
 - en-us-a53ee708f8f05d570a3095cbc9cec948.js: 23.77 KB (3.85 KB gzipped)
 - open-metaverse-pool-59bc71f74395f0d5c23846763cac5473.css: 3.34 KB (1.05 KB gzipped)
 - open-metaverse-pool-d6dd18373c82589eeb17142525b25fc2.js: 201.91 KB (22.52 KB gzipped)
 - vendor-2f058756369b859fa3626ebe08d7b15f.js: 1005.77 KB (210.63 KB gzipped)
 - vendor-6de03bdc10f4c279bf86a435b7667839.css: 144.2 KB (26.03 KB gzipped)
 - browsercheck-9f04135b31b376ccd5866c1fc0caf2f0.js: 119 B (124 B gzipped)

**Comment by NotoriousPyro** [comment]
That's because I've not developed it to that version yet - I will add the supported versions to the readme. Good to see you got it working.
